### ISSUE TITLE
Consider describing advantages over pylint support in python extension

### ISSUE THREAD

**Issue by parched** [microsoft/vscode-pylint#38]
I'm currently using pylint with the python extension and am wondering if I should switch to this extension. What benefits does it give? Is it performance?

**Comment by brettcannon** [comment]
Direct benefits are:

- It's **much** faster (as long as you don't specify the path to Pylint, else it's the same)
- Pylint is included (so you don't have to install it)
- You have more control of the severity of error codes

Indirectly:

- We can update this w/o updating the entire Python extension
- It's easier to contribute to since nearly all the code for this extension is written in Python

FYI we will be removing Pylint support in the Python extension once we are happy with this extension.
