### ISSUE TITLE
Memory Ballooning and eventual OOM

### ISSUE THREAD

**Issue by AccidentallyTheCable** [microsoft/vscode-pylint#391]
Recently Ive been seeing a consistent problem with this extension when im using it. The memory usage for this extension will slowly grow as I work, eventually consuming 50% or more of my 4GB dev environment. Eventually performance of everything on the system plummets, and I have to kill the entire vscode server, then reload the window to start it back up.

This is after ~18 hours of use (about 1/2 time running idle). Output is from `ps xauf`

`0.0 77.1 3552456 3237316 ?     Dl   Sep17   8:06      |   \_ /data/venv/python-provisioner/bin/python3 /home/cableninja/.vscode-server/extensions/ms-python.pylint-2023.6.0/bundled/tool/lsp_server.py`

This system only has 4GB of ram, and thats already been bumped twice now because of this. Its only expanding how long it takes before I have to restart vscode.  Once I kill and restart everything, it will return to 0 (or almost 0) usage, only to start ballooning again when I start heavily working on things.

vscode-pylint version: `2023.6.0`

VSCode Version:
```
Version: 1.81.1 (system setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z (1 mo ago)
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
```

Remote System information:
LXC Container
Debian GNU/Linux 11
Kernel: `5.19.17-1-pve`

Python Version: `3.9.2`
PyLint version: `2.16.4`

**Comment by karthiknadig** [comment]
@AccidentallyTheCable This should really be filed on `pylint`. We had a similar issue before and it was addressed in pylint: https://github.com/microsoft/vscode-pylint/issues/280

A workaround is to set the `pylint.path`. This will get pylint to run as a command line tool, instead of running it in memory using the server. You can either point it to `pylint` executable using `"pylint.path": [".venv/bin/pylint"]` or use the interpreter `"pylint.path":[ ".venv/bin/python", "-m", "pylint"]`. 

You can also set it to just `pylint` ( `"pylint.path": ["pylint"]`) but you would have to start VS Code from an activated environment:
```
> cd <your project>
> source ./.venv/bin/activate
> code .
```
