### ISSUE TITLE
Terrible performance after upgrade to VSCode 1.83.1

### ISSUE THREAD

**Issue by romado77** [microsoft/vscode-pylint#420]
I have observed a substantial decrease in the performance of Pylint following the upgrade of VSCode to version 1.83.1. For instance, when typing a completely valid line of code such as `test = int(test)`, Pylint underlines each word in the statement, and it takes 10-15 seconds for all underlining to disappear. Occasionally, it fails to clear the underlines altogether, indicating a syntax error despite no apparent issues. Although restarting VSCode temporarily resolves the problem, the overall performance remains unsatisfactory. This behavior was not present in previous versions of the software.
I'm uncertain whether this issue is related to the VSCode upgrade or Pylint itself. I didn't take note of the Pylint version in the previous VSCode version since I never encountered any problems with Pylint before. At this point, I've had to disable the Pylint extension because it has become intolerable and disruptive to my work.

pylint 3.0.1
astroid 3.0.0
Python 3.9.15 (main, Oct 20 2022, 11:19:47) 
[Clang 14.0.0 (clang-1400.0.29.102)]

**Comment by karthiknadig** [comment]
@romado77 Please share the logs so we can see if this is due to extension or if this should be moved to `pylint` itself
![image](https://github.com/microsoft/vscode-pylint/assets/3840081/6bf0ebed-b885-4a98-957a-2545e3e43931)

Note that, the major change between previous and current release is that we went from pylint 2.* to pylint 3.*

**Comment by sweemer** [comment]
I also experienced a slowdown after the last upgrade, and discovered that it was due to setting `"pylint.lintOnChange": true`. If I set this to false then the behavior is much more tolerable.

Probably this setting needs an additional setting to control how long to wait after a change, with a default value of say 500ms. Currently it seems that it starts linting after each key stroke, which gets backlogged way too easily.

**Comment by karthiknadig** [comment]
@sweemer You can turn on auto-save, and turn of linting on change to get similar effect of having a delay.

**Comment by yaroslavsadin** [comment]
+1, wait time is 5 to 10 seconds

**Comment by karthiknadig** [comment]
Please share the logs for this as requested here: https://github.com/microsoft/vscode-pylint/issues/420#issuecomment-1764773458
If possible capture a cpu profile.

**Comment by karthiknadig** [comment]
I pushed a potential fix for this in 2023.11.13191929 pre-release version. Please try it out. If the issue continues to exist, please provide the following:
1. Your settings workspace and user settings.
2. Logs from Output > pylint logs

**Comment by karthiknadig** [comment]
Because we have not heard back with the information we requested, we are closing this issue for now. If you are able to provide the info later on then we will be happy to re-open this issue to pick up where we left off.
