### ISSUE TITLE
`pylint.ignorePatterns` doesn't work with glob pattern as documented

### ISSUE THREAD

**Issue by Mutantpenguin** [microsoft/vscode-pylint#445]
### Problem
The documentation of `pylint.ignorePatterns` states that it works with glob patterns like described in https://code.visualstudio.com/docs/editor/glob-patterns

But this is not true.

Your implementation uses `match` from `pathlib` that (as far as I understand it) doesn't work with glob patterns.

### Example
```python
import pathlib

def is_match(patterns: list[str], file_path: str) -> bool:
    """Returns true if the file matches one of the glob patterns."""
    if not patterns:
        return False
    return any(pathlib.Path(file_path).match(pattern) for pattern in patterns)

patterns: list[str] = [
    "**/a_path/**/*.py",
]

file_path: str = "/a_path/a_subpath/a_subpath/my_file.py"

print(is_match(patterns, file_path))
```

This prints out `False`.

Replacing `**/a_path/**/*.py` with `**/a_path/**/**/*.py` will return `True`.

### External Sources
Here you can see, that the glob pattern `**/a_path/**/*.py` should work:
* https://www.digitalocean.com/community/tools/glob?comments=true&glob=%2A%2A%2Fa_path%2F%2A%2A%2F%2A.py&matches=false&tests=%2Fa_path%2Fa_subpath%2Fa_subpath%2Fmy_file.py

**Comment by karthiknadig** [comment]
This is a documentation bug. We use `fnmatch` style glob patterns, this is the documentation for it: https://github.com/microsoft/vscode-pylint/pull/449

**Comment by Mutantpenguin** [comment]
I don't think that this is the case.

The function `is_match` I used in my example is a direct copy from your code and doesn't use `fnmatch`.

Apart from that I just tried out the fnmatch syntax and it didn't work either.

It works if I change `return any(pathlib.Path(file_path).match(pattern) for pattern in patterns)` to `any(fnmatch.fnmatch(file_path, pattern) for pattern in patterns)`.

So I am pretty sure that the match from `pathlib` doesn't use `fnmatch` in ternally.

**Comment by karthiknadig** [comment]
@Mutantpenguin that is a bug. Would you like to create a PR with the change.

**Comment by karthiknadig** [comment]
@Mutantpenguin I can verify that pathlib is using `fnmatch` here:
<img width="850" alt="image" src="https://github.com/microsoft/vscode-pylint/assets/3840081/c85ce8db-c810-41a1-af0b-cd539dafc446">

As for using Glob, as defined by VS Code. VS Code had to do a custom implementation of Glob because there is no standard definition that all agree on (see here: https://github.com/microsoft/vscode/blob/main/src/vs/base/common/glob.ts). Python itself does not have a glob pattern matcher, the `glob` stdlib package in python performs file system operation to perform glob pattern matching, and the API has a warning that for large directories this can hinder performance severely. I would really avoid that package.

I agree the difference makes it hard to figure out what is right pattern format to use. We are open for recommendations on this.

**Comment by Mutantpenguin** [comment]
> @Mutantpenguin that is a bug. Would you like to create a PR with the change.

Just did so. If these changes are ok I would do the same for vscode-mypy and vscode-flake8 as they use the same implementation.

As for the glob patterns: I think that's a great pity, but I can understand the reasoning behind it.
