### ISSUE TITLE
--rcfile arg must be set to an absolute path?

### ISSUE THREAD

**Issue by yarimiz** [microsoft/vscode-pylint#453]
I've been trying to set a different .pylintrc file per project, as I work with 10s of repositories, each might have different settings.
Since pylint is not an extension, this seems impossible.

When I'm setting the following args in my user's settings.json, the pylint file is not being found by pylint:
either a relative path
`
"pylint.args": [
        "--rcfile=.pylintrc"
    ]
`

or using ${workspaceFolder} var
`
"pylint.args": [
        "--rcfile=${workspaceFolder}.pylintrc"
    ]
`

Both generates:
> [info] The config file ${workspaceFolder}.pylintrc doesn't exist!

The only option that works for me is specifying the absolute path of the rcfile, but as I mentioned, each repository has it's own file.
This works:
`
"pylint.args": [
        "--rcfile=/home/actual/path/to/the/file/.pylintrc"
    ],
`

Am I missing something? Or is the extension does not support relative paths for args?
I don't intend to set workspace setting for pylint for every project I'm using, this is just wrong, especially where all the rcfiles have the default name of `.pylintrc` and found in the root folder of each project.

**Comment by karthiknadig** [comment]
@yarimiz User settings are not resolved in the same way, because they don't belong to a workspace. If you can share the full logs it should show you the settings being used at the beginning.

This is how it works:
* both user settings and workspace settings have `pylint.args`, then pylint args from workspace is used. Since this is workspace bound this is resolved with `workspaceFolder` substitutions. The User setting is unresolved and preserved, and is applied to files opened in the editor that do not belong to the workspace.
* Only user setting has `pylint.args`. The setting is copied to the workspace, and resolved in the workspace context. The User setting is unresolved and preserved, and is applied to files opened in the editor that do not belong to the workspace.

Please share this part:
![image](https://github.com/microsoft/vscode-pylint/assets/3840081/2fc350c4-c313-453a-ab47-1d0cce9e290a)

**Comment by karthiknadig** [comment]
Because we have not heard back with the information we requested, we are closing this issue for now. If you are able to provide the info later on then we will be happy to re-open this issue to pick up where we left off.
