### ISSUE TITLE
Add link to Terminal's pylint link or tooltip

### ISSUE THREAD

**Issue by CTimmerman** [microsoft/vscode-pylint#537]
Currently people need to use both hands to use a pylint issue link in the Terminal:
![image](https://github.com/microsoft/vscode/assets/9662163/81f496f2-944e-475c-b87b-5b463627bbfd)

It would be nice if that worked like the Problems tab or even the Terminal folder links:
![image](https://github.com/microsoft/vscode/assets/9662163/fb2b72ab-1a7a-4e43-8075-3af3de832076)

**Comment by karthiknadig** [comment]
Thanks for the feature request! We are going to give the community 60 days from when this issue was created to provide 7 👍 upvotes on the opening comment to gauge general interest in this idea. If there's enough upvotes then we will consider this feature request in our future planning. If there's unfortunately not enough upvotes then we will close this issue.

**Comment by eleanorjboyd** [comment]
Thank you for submitting your feature request and everyone who considered it! Unfortunately, this issue did not receive enough votes over the allotted time, and so we are closing the issue.
